/ AUTO-GENERATED by q-test scaffold - review before relying on it.
/ Generated from: examples/math.q
/ Regenerate with: q bin/qtest.q generate examples/math.q

system "l examples/math.q";

\d .mathTest
testAdd:{.qt.gen.forAll[(.qt.gen.int[-100;100];.qt.gen.int[-100;100]);{[p1;p2] .qt.assertNoErrorArgs[.math.add;(p1;p2);"survives generated input"];1b};".math.add survives random input (auto-generated - review the generators above, real arg types may differ)"]};
testSub:{.qt.gen.forAll[(.qt.gen.int[-100;100];.qt.gen.int[-100;100]);{[p1;p2] .qt.assertNoErrorArgs[.math.sub;(p1;p2);"survives generated input"];1b};".math.sub survives random input (auto-generated - review the generators above, real arg types may differ)"]};
testGetPrimesLessThan:{.qt.gen.forAll[(.qt.gen.int[-100;100]);{[p1] .qt.assertNoErrorArgs[.math.getPrimesLessThan;enlist p1;"survives generated input"];1b};".math.getPrimesLessThan survives random input (auto-generated - review the generators above, real arg types may differ)"]};

\d .
.qt.register[`.mathTest];
