/ q-test :: test-file scaffolding
/ .qt.scaffold.forFile[srcPath;outDir] loads a plain .q source file, finds
/ the functions it defines, and writes a ready-to-run *_test.q file next to
/ it: a .qt.gen.forAll smoke test per function (generic int generators - a
/ starting point, not a finished test) for everything it can determine the
/ arity of.
/ Unlike q-desc's testFramework (which requires a //@param annotation
/ comment for every parameterized function before it will fuzz it), this
/ needs no annotation step - it reads real arity off the loaded function
/ via `value`, generates its best guess, and clearly marks the guess as
/ something to refine, in both the file header and each generated case.

\d .qt

/ ---- source inspection -----------------------------------------------------
/ first namespace a source file switches into, if any (a line reading
/ exactly "\d .foo"). () wrapped as ` if none found.
scaffold.i.findNamespace:{[srcPath]
  lines:read0 hsym `$srcPath;
  matches:lines where lines like "\\d *";
  if[0=count matches; :`];
  ns:`$3_first matches;
  $[ns~`.; `; ns]
 };

scaffold.i.isFunc:{[v] (type v) within 100 112h};

/ arity of a plain lambda (100h); -1 if not a plain lambda (projection,
/ composition, primitive, ...) - those are skipped, not guessed at.
/ Note every lambda reports arity >=1 here, even {[] ...} (explicit empty
/ params) and bare {...} with no x/y/z referenced at all - q always gives
/ a plain lambda at least one declared parameter slot.
scaffold.i.arity:{[f] $[100h=type f; count value[f] 1; -1]};

/ every plain-function child directly under namespace ns. `key ns` includes
/ a spurious leading empty-symbol entry (an internal namespace artifact,
/ not a real child) - drop it before qualifying names.
scaffold.i.functionsIn:{[ns]
  names:key[ns] where key[ns]<>`;
  quals:{[ns;nm] ` sv ns,nm}[ns] each names;
  quals where scaffold.i.isFunc each value each quals
 };

/ functions that appeared at root between two `key `.` snapshots
scaffold.i.newRootFunctions:{[before]
  new:(key `.) except before;
  new where scaffold.i.isFunc each value each new
 };

/ ---- code generation --------------------------------------------------------
scaffold.i.titleCase:{[s] (upper first s),1_s};

scaffold.i.testName:{[fname] `$"test",scaffold.i.titleCase string last ` vs fname};

/ one generated test-case line for function fname (fully qualified symbol),
/ () if its arity couldn't be determined (skipped). Every real lambda goes
/ through the same forAll-based smoke test, since q reports every lambda
/ as arity >=1 (see scaffold.i.arity) - there is no separate niladic case.
scaffold.i.genCase:{[fname]
  ar:scaffold.i.arity value fname;
  $[ar<0; (); ar>8; (); scaffold.i.genForAllCase[fname;ar]]
 };

scaffold.i.genForAllCase:{[fname;ar]
  tn:scaffold.i.testName fname;
  fs:string fname;
  ps:`$"p",/:string 1+til ar;
  psStr:";" sv string ps;
  gensStr:";" sv (ar#enlist ".qt.gen.int[-100;100]");
  argListStr:$[ar=1; "enlist ",first string ps; "(",psStr,")"];
  / no leading whitespace: an indented top-level statement silently fails
  / to register at all when the file is loaded (unlike inside a {} body,
  / where indentation is only cosmetic) - see q_kdb_gotchas.md
  enlist string[tn],":{.qt.gen.forAll[(",gensStr,");{[",psStr,"] .qt.assertNoErrorArgs[",fs,";",argListStr,";\"survives generated input\"];1b};\"",fs," survives random input (auto-generated - review the generators above, real arg types may differ)\"]};"
 };

/ ---- orchestration -----------------------------------------------------------
scaffold.i.baseName:{[srcPath]
  noExt:$[srcPath like "*.q"; -2_srcPath; srcPath];
  parts:"/" vs ssr[noExt;"\\";"/"];
  last parts
 };

/ generate a *_test.q scaffold for srcPath, write it under outDir, return a
/ summary dict `written`generated`skipped!(filePath;n;list of skipped names)
scaffold.forFile:{[srcPath;outDir]
  before:key `.;
  ns:scaffold.i.findNamespace srcPath;
  system "l ",srcPath;
  fns:$[ns~`; scaffold.i.newRootFunctions before; scaffold.i.functionsIn ns];

  cases:scaffold.i.genCase each fns;
  skipped:fns where 0=count each cases;
  kept:fns where 0<count each cases;
  bodyLines:raze cases where 0<count each cases;

  base:scaffold.i.baseName srcPath;
  testNs:`$"." ,base,"Test";
  outPath:outDir,"/",base,"_test.q";

  header:(
    "/ AUTO-GENERATED by q-test scaffold - review before relying on it.";
    "/ Generated from: ",srcPath;
    "/ Regenerate with: q bin/qtest.q generate ",srcPath;
    "";
    "system \"l ",srcPath,"\";";
    "";
    "\\d ",string testNs);
  footer:("";"\\d .";".qt.register[`",string[testNs],"];");

  lines:header,bodyLines,footer;
  (hsym `$outPath) 0: lines;

  `written`generated`skipped!(outPath;count kept;skipped)
 };

\d .
